fragment seo on SEO {
  focuskw
  metaDesc
  metaKeywords
  metaRobotsNofollow
  metaRobotsNoindex
  opengraphDescription
  opengraphImage
  opengraphTitle
  title
  twitterDescription
  twitterImage
  twitterTitle
}
