query GET_TEACHERS_PAGE_BY_URI($uri: String) {
  page: pageBy(uri: $uri) {
    title
    content
    featuredImage {
      altText
      heroLarge: sourceUrl(size: HERO_LARGE)
      heroMedium: sourceUrl(size: HERO_MEDIUM)
      heroSmall: sourceUrl(size: HERO_SMALL)
    }
    wayWeWorkGroup {
      wayWeWork {
        text
        title
        image {
          thumbnail: sourceUrl(size: THUMBNAIL)
          medium: sourceUrl(size: MEDIUM)
        }
      }
    }
  }
}
