#import "./Fragments/PageContent.gql"
#import "./Fragments/ImageHero.gql"

query GET_PAGE_BY_URI($uri: String) {
  page: pageBy(uri: $uri) {
    ...pageContent
    forStudentsAndParents {
      forParents {
        text
      }
      forStudents {
        text
      }
    }
    prices {
      price
      title
    }
    forStudentsAndParentsGroup {
      student {
        text
      }
      parents {
        text
      }
    }
    pricesGroup {
      image {
        ...imageHero
      }
      prices {
        price
        title
        recommended
      }
    }
  }
}
