#import "./Fragments/PageContent.gql"
#import "./Fragments/ImageHero.gql"

query GET_FRONT_PAGE {
  page: pageBy(pageId: 1379) {
    ...pageContent
    uspsFrontPageGroup {
      usps {
        text
      }
      offers {
        text
      }
    }
    servicesGroup {
      servicesLabel
      services {
        title
        usps {
          text
        }
        link {
          target
          title
          url
          relativeUrl
        }
      }
      servicesImage {
        ...imageHero
      }
    }
  }
}
