#import "./Fragments/ImageArchive.gql"
#import "./Fragments/Seo.gql"

query GET_POST_BY_URI($uri: ID!) {
  post(id: $uri, idType: URI) {
    featuredImage {
      node {
        ...imageArchive
      }
    }
    content
    title
    date
    slug
    seo {
      ...seo
    }
  }
}
