#import "./Fragments/ImageArchive.gql"

query getSiteDetails {
  siteDetails {
    socialMediaGroup {
      facebook
      fieldGroupName
      instagram
      linkedin
      twitter
    }
    addressesGroup {
      email
      kvk
      phonenumber
      addresses {
        city
        latitude
        longitude
        street
        zipcode
        image {
          ...imageArchive
        }
      }
    }
  }
}
