#import "./Fragments/ImageArchive.gql"

query getSiteDetails {
  siteDetails {
    socialMediaGroup {
      facebook
      fieldGroupName
      instagram
      linkedin
      twitter
    }
    heroImageGroup {
      image {
        altText
        heroLarge: sourceUrl(size: HERO_LARGE)
        heroMedium: sourceUrl(size: HERO_MEDIUM)
        heroSmall: sourceUrl(size: HERO_SMALL)
      }
    }
    addressesGroup {
      email
      kvk
      phonenumber
      addresses {
        city
        latitude
        longitude
        street
        zipcode
        image {
          ...imageArchive
        }
      }
    }
  }
}
